### ISSUE TITLE
Similar mod

### ISSUE THREAD

**Issue by Michael21107** [SuleMareVientu/StreetVendorsV-ScriptHookV#3]
hey. as this looks pretty similar, i wanted to make sure its not stolen from you https://www.lcpdfr.com/downloads/gta5mods/misc/47161-streethotdogs/

**Comment by SuleMareVientu** [comment]
From a quick look in IDA it seems to be my script. There is no problem with them redistributing the binary but they should link to the license and give proper credits. 
My code is distributed under CC BY-NC-SA 4.0: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en

**Comment by Michael21107** [comment]
since the author doesn't do that and even claims it as her own (https://www.lcpdfr.com/downloads/gta5mods/misc/47161-streethotdogs/?do=findComment&comment=344324) i would love if you reported it, we don't need such people in the community
